### ISSUE TITLE
issue cerating sealedsecret.json file

### ISSUE THREAD

**Issue by sudhirbatchu9383** [dnmahendra/kube-secret-manager#1]
Error getting

(node:48111) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/Users/sudhirbatchu/projects/kube-secret-manager/lib/..apps/blaze/development/sealedSecrets.json'
    at Object.openSync (fs.js:440:3)
    at Object.writeFileSync (fs.js:1265:35)
    at /Users/sudhirbatchu/projects/kube-secret-manager/lib/encrypt.js:35:12
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:48111) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

**Comment by sudhirbatchu9383** [comment]
> Error getting
> 
> (node:48111) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/Users/sudhirbatchu/projects/kube-secret-manager/lib/..apps/blaze/development/sealedSecrets.json'
> at Object.openSync (fs.js:440:3)
> at Object.writeFileSync (fs.js:1265:35)
> at /Users/sudhirbatchu/projects/kube-secret-manager/lib/encrypt.js:35:12
> at processTicksAndRejections (internal/process/task_queues.js:93:5)
> (node:48111) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

I have fixed a small issue in the path defined in the code ../apps instead ..apps
